# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
